# SwiftLint Configuration for Virgo

# Paths to include during linting
included:
  - Virgo
  - VirgoTests
  - VirgoUITests

# Paths to exclude during linting
excluded:
  - Virgo.xcodeproj
  - DerivedData
  - .build
  - .git

# Disabled rules
disabled_rules:
  - trailing_whitespace # Allow trailing whitespace for now
  - todo # Allow TODO comments
  - force_cast # Sometimes force casting is necessary
  - force_try # Sometimes force try is acceptable in tests
  - file_length # Temporarily disable for performance commit
  - type_body_length # Temporarily disable for performance commit

# Opt-in rules
opt_in_rules:
  - empty_count
  - empty_string
  - explicit_init
  - first_where
  - sorted_first_last
  - contains_over_first_not_nil
  - last_where
  - reduce_boolean
  - contains_over_range_nil_comparison

# Customized rules
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 200
  error: 300

file_length:
  warning: 400
  error: 500

identifier_name:
  min_length:
    warning: 1
    error: 1
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - i
    - j
